{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 108,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import dlc_practical_prologue as prologue\n",
    "\n",
    "from torch import optim\n",
    "from torch.nn import functional as F\n",
    "from torch import nn\n",
    "from torch.autograd import Variable"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "metadata": {},
   "outputs": [],
   "source": [
    "def hand_comparison(digit_1, digit_2):\n",
    "    \n",
    "    predicted_class = torch.zeros(digit_1.size(0))\n",
    "    \n",
    "    _, digit_1 = torch.max(digit_1, 1)\n",
    "    _, digit_2 = torch.max(digit_2, 1)\n",
    "    \n",
    "    for i in range(digit_1.size(0)):\n",
    "        if digit_1[i] <= digit_2[i]:\n",
    "            predicted_class[i] = 1\n",
    "    \n",
    "    return predicted_class"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compute_nb_errors(model, data_input, data_target, mini_batch_size):\n",
    "\n",
    "    nb_data_errors = 0\n",
    "\n",
    "    for b in range(0, data_input.size(0), mini_batch_size):\n",
    "        ##################_, _, result = model(data_input.narrow(0, b, mini_batch_size))\n",
    "        # Make a function that gives the reult calculating by hand\n",
    "        # Result is the given result with data_input\n",
    "        digit_1, digit_2 = model(data_input.narrow(0, b, mini_batch_size))\n",
    "        predicted_class = hand_comparison(digit_1, digit_2) # Gives 0 or 1, second output of the function max\n",
    "        for k in range(mini_batch_size):\n",
    "            if data_target[b + k] != predicted_class[k]:\n",
    "                nb_data_errors = nb_data_errors + 1\n",
    "\n",
    "    return nb_data_errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 111,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compute_nb_errors_comparison(model, data_input, data_target, data_classes, mini_batch_size):\n",
    "    \n",
    "    nb_data_errors = 0\n",
    "    nb_errors_comparison = 0\n",
    "    nb_errors_digit1 = 0\n",
    "    nb_errors_digit2 = 0\n",
    "    \n",
    "    for b in range(0, data_input.size(0), mini_batch_size):\n",
    "        digit1, digit2, result = model(data_input.narrow(0, b, mini_batch_size))\n",
    "        _, predicted_classes = torch.max(result, 1)\n",
    "        _, predicted_classes_digit1 = torch.max(digit1, 1)\n",
    "        _, predicted_classes_digit2 = torch.max(digit2, 1)\n",
    "        for k in range(mini_batch_size):\n",
    "            if data_target[b + k] != predicted_classes[k]:\n",
    "                nb_data_errors = nb_data_errors + 1\n",
    "            if data_classes[b + k, 0] != predicted_classes_digit1[k]:\n",
    "                nb_errors_digit1 += 1\n",
    "            if data_classes[b + k, 1] != predicted_classes_digit2[k]:\n",
    "                nb_errors_digit2 += 1\n",
    "            if ((predicted_classes_digit1[k] < predicted_classes_digit2[k]) and predicted_classes[k] == 0):\n",
    "                nb_errors_comparison += 1\n",
    "            if ((predicted_classes_digit1[k] > predicted_classes_digit2[k]) and predicted_classes[k] == 1):\n",
    "                nb_errors_comparison += 1\n",
    "            \n",
    "    return nb_data_errors, nb_errors_comparison, nb_errors_digit1, nb_errors_digit2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 112,
   "metadata": {},
   "outputs": [],
   "source": [
    "def accuracy_based_on_imgs(model, data_input, data_target):\n",
    "    digit1, digit2, result = model(data_input)\n",
    "\n",
    "    _, predictions1 = torch.max(digit1.data, 1)\n",
    "    _, predictions2 = torch.max(digit2.data, 1)\n",
    "    \n",
    "    predictions = (predictions1 <= predictions2).long()\n",
    "    well_predicted_count = (predictions == data_target).sum().item()\n",
    "\n",
    "    return 1 - well_predicted_count / data_input.size(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "metadata": {},
   "outputs": [],
   "source": [
    "def accuracy_based_on_result(model, data_input, data_target):\n",
    "    digit1, digit2, result = model(data_input)\n",
    "    \n",
    "    _, predictions = torch.max(result.data, 1)\n",
    "    well_predicted_count = (predictions == test_target_).sum().item()\n",
    "    \n",
    "    return 1 - well_predicted_count / total"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "metadata": {},
   "outputs": [],
   "source": [
    "######################################################################\n",
    "def train_model_decay(model, train_input, train_target, train_classes, nb_epochs, mini_batch_size):\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    eta0 = 1e-1\n",
    "    decay = 1\n",
    "\n",
    "    for e in range(nb_epochs):\n",
    "        eta = (1 / (1 + decay*nb_epochs)) * eta0\n",
    "        optimizer = optim.SGD(model.parameters(), lr = eta)\n",
    "        \n",
    "        for b in range(0, train_input.size(0), mini_batch_size):\n",
    "            digit1, digit2, result = model(train_input.narrow(0, b, mini_batch_size))\n",
    "            \n",
    "            loss_result = criterion(result, train_target.narrow(0, b, mini_batch_size))\n",
    "            loss_digit1 = criterion(digit1, train_classes[:,0].narrow(0, b, mini_batch_size))\n",
    "            loss_digit2 = criterion(digit2, train_classes[:,1].narrow(0, b, mini_batch_size))\n",
    "            loss = loss_result + loss_digit1 + loss_digit2\n",
    "            \n",
    "            model.zero_grad()\n",
    "            loss.backward()\n",
    "            optimizer.step()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 115,
   "metadata": {},
   "outputs": [],
   "source": [
    "######################################################################\n",
    "def train_model(model, train_input, train_target, train_classes, nb_epochs, mini_batch_size):\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    eta = 1e-3\n",
    "    optimizer = optim.Adam(model.parameters(), lr = eta)\n",
    "    \n",
    "    for e in range(nb_epochs):    \n",
    "        \n",
    "        for b in range(0, train_input.size(0), mini_batch_size):\n",
    "            digit1, digit2 = model(train_input.narrow(0, b, mini_batch_size))\n",
    "            \n",
    "            loss_digit1 = criterion(digit1, train_classes[:,0].narrow(0, b, mini_batch_size))\n",
    "            loss_digit2 = criterion(digit2, train_classes[:,1].narrow(0, b, mini_batch_size))\n",
    "            loss = loss_digit1 + loss_digit2\n",
    "            \n",
    "            model.zero_grad()\n",
    "            loss.backward()\n",
    "            optimizer.step()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "metadata": {},
   "outputs": [],
   "source": [
    "######################################################################   \n",
    "class ConvNoWS(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(ConvNoWS, self).__init__()\n",
    "        \n",
    "        #Input channels = 1, output channels = 32\n",
    "        self.layer1 = nn.Sequential(\n",
    "            nn.Conv2d(1, 32, kernel_size=3, padding=1),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(kernel_size=2))\n",
    "        \n",
    "        #Input channels = 32, output channels = 64\n",
    "        self.layer2 = nn.Sequential(\n",
    "            nn.Conv2d(32, 64, kernel_size=2, padding=1),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(kernel_size=2))\n",
    "\n",
    "        \n",
    "        # Formula to get out_put size (in_size - kernel_size + 2*(padding)) / stride) + 1\n",
    "        # first layer (14-5+2*2)/1 +1 = 14/2 = 7\n",
    "        # second layer (7 -4 +2*2)/1 +1 = 8/2 = 4\n",
    "        # 4 * 4 * 64 input features, 1000 output features\n",
    "        self.fc1 = nn.Linear(4 * 4 * 64, 1000)\n",
    "        \n",
    "        # 1000 input features, 2 output features\n",
    "        self.fc2 = nn.Linear(1000, 10)\n",
    "        \n",
    "    def forward(self, x):\n",
    "        \n",
    "        first_digit = x[:,[0]]\n",
    "        second_digit = x[:,[1]]\n",
    "\n",
    "        first_digit = self.layer1(first_digit)\n",
    "        second_digit = self.layer1(second_digit)\n",
    "        \n",
    "        first_digit = self.layer2(first_digit)\n",
    "        second_digit = self.layer2(second_digit)\n",
    "    \n",
    "        first_digit = F.relu(self.fc1(first_digit.view(-1, 4 * 4 * 64)))\n",
    "        second_digit = F.relu(self.fc1(second_digit.view(-1, 4 * 4 * 64)))\n",
    "        \n",
    "        first_digit = self.fc2(first_digit)\n",
    "        second_digit = self.fc2(second_digit)\n",
    "        \n",
    "        return first_digit, second_digit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_tests(n):\n",
    "    M = []\n",
    "    for k in range (0, n):\n",
    "        L = []\n",
    "        _, _, _, test_input, test_target, test_classes =  prologue.generate_pair_sets(1000)\n",
    "        L.append(test_input)\n",
    "        L.append(test_target)\n",
    "        L.append(test_classes)\n",
    "        M.append(L)\n",
    "    return M\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "ERROR! Session/line number was not unique in  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-118-146478805cd5>\", line 4, in <module>\n",
      "    = prologue.generate_pair_sets(1000)\n",
      "  File \"/Users/churchhyll/Documents/EPFL/4ème année/Semestre VIII/Deep Learning/Project/Working folder/Project 1/dlc_practical_prologue.py\", line 136, in generate_pair_sets\n",
      "    train_set = datasets.MNIST(data_dir + '/mnist/', train = True, download = True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py\", line 79, in __init__\n",
      "    self.download()\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py\", line 140, in download\n",
      "    os.makedirs(self.raw_folder, exist_ok=True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 223, in makedirs\n",
      "    mkdir(name, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './data'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      " database. History logging moved to new session 76\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-118-146478805cd5>\", line 4, in <module>\n",
      "    = prologue.generate_pair_sets(1000)\n",
      "  File \"/Users/churchhyll/Documents/EPFL/4ème année/Semestre VIII/Deep Learning/Project/Working folder/Project 1/dlc_practical_prologue.py\", line 136, in generate_pair_sets\n",
      "    train_set = datasets.MNIST(data_dir + '/mnist/', train = True, download = True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py\", line 79, in __init__\n",
      "    self.download()\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py\", line 140, in download\n",
      "    os.makedirs(self.raw_folder, exist_ok=True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 223, in makedirs\n",
      "    mkdir(name, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './data'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-118-146478805cd5>\", line 4, in <module>\n",
      "    = prologue.generate_pair_sets(1000)\n",
      "  File \"/Users/churchhyll/Documents/EPFL/4ème année/Semestre VIII/Deep Learning/Project/Working folder/Project 1/dlc_practical_prologue.py\", line 136, in generate_pair_sets\n",
      "    train_set = datasets.MNIST(data_dir + '/mnist/', train = True, download = True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py\", line 79, in __init__\n",
      "    self.download()\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/torchvision/datasets/mnist.py\", line 140, in download\n",
      "    os.makedirs(self.raw_folder, exist_ok=True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 213, in makedirs\n",
      "    makedirs(head, exist_ok=exist_ok)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/os.py\", line 223, in makedirs\n",
      "    mkdir(name, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './data'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3071, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/Users/churchhyll/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "    \n",
    "######################################################################   \n",
    "    \n",
    "train_input, train_target, train_classes, _, _, _ \\\n",
    "    = prologue.generate_pair_sets(1000)\n",
    "    \n",
    "\n",
    "# train_input, train_target, train_classes \\\n",
    "#     = Variable(train_input), Variable(train_target), Variable(train_classes)\n",
    "# test_input, test_target, test_classes \\\n",
    "#     = Variable(test_input), Variable(test_target), Variable(test_classes)\n",
    "\n",
    "\n",
    "model = ConvNoWS()\n",
    "nb_epochs = 25\n",
    "mini_batch_size = 100\n",
    "\n",
    "train_model(model, train_input, train_target, train_classes, nb_epochs, mini_batch_size)\n",
    "L = get_tests(10)\n",
    "\n",
    "\n",
    "nb_train_errors = compute_nb_errors(model, train_input, train_target, mini_batch_size)\n",
    "#accuracy_based_on_imgs = accuracy_based_on_imgs(model, train_input, train_target)\n",
    "#accuracy_based_on_result = accuracy_based_on_result(model, train_input, train_target)\n",
    "\n",
    "print('train error ConvNoWS {:0.2f}%{:d}/{:d}'.format((100 * nb_train_errors) / train_input.size(0),\n",
    "                                        nb_train_errors, train_input.size(0)))\n",
    "#print('train accuracy_based_on_imgs ConvNoWS {:0.2f}%{:d}/{:d}'.format((100 * accuracy_based_on_imgs) / train_input.size(0),\n",
    "#                                        accuracy_based_on_imgs, train_input.size(0)))\n",
    "#print('train accuracy_based_on_result ConvNoWS {:0.2f}%{:d}/{:d}'.format((100 * accuracy_based_on_result) / train_input.size(0),\n",
    "#                                        accuracy_based_on_result, train_input.size(0)))\n",
    "\n",
    "nb_moy_test_error = 0\n",
    "#average_test_error_basedOnImages = 0\n",
    "#average_test_error_basedOnResults = 0\n",
    "\n",
    "for k in range (0, len(L)):\n",
    "    nb_test_errors = compute_nb_errors(model, L[k][0], L[k][1], mini_batch_size)\n",
    "    #test_error_basedOnImages = accuracy_based_on_imgs(model, L[k][0], L[k][1])\n",
    "    #test_error_basedOnResults = accuracy_based_on_result(model, L[k][0], L[k][1])\n",
    "    \n",
    "    nb_moy_test_error += nb_test_errors\n",
    "    #average_test_error_basedOnImages += test_error_basedOnImages\n",
    "    #average_test_error_basedOnResults += test_error_basedOnResults\n",
    "\n",
    "    print('test error ConvNoWS {:0.2f}% {:d}/{:d}'.format((100 * nb_test_errors) / L[k][0].size(0),\n",
    "                                                nb_test_errors, L[k][0].size(0)))\n",
    "    #print('train accuracy_based_on_imgs ConvNoWS {:0.2f}%{:d}/{:d}'.format((100 * test_error_basedOnImages) / L[k][0].size(0),\n",
    "    #                                    test_error_basedOnImages, L[k][0].size(0)))\n",
    "    #print('train accuracy_based_on_result ConvNoWS {:0.2f}%{:d}/{:d}'.format((100 * test_error_basedOnResults) / L[k][0].size(0),\n",
    "    #                                    test_error_basedOnResults, L[k][0].size(0)))\n",
    "print('Average test error ConvNoWS {:0.2f}% {:0.1f}/{:d}'.format((100*nb_moy_test_error/10) / L[0][0].size(0),nb_moy_test_error/10, L[0][0].size(0) ))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
